export enum ENotificationType {
  TOPIC_LIKED = "TOPIC_LIKED",
  TOPIC_FOLLOWED = "TOPIC_FOLLOWED",
  TOPIC_COMMENTED = "TOPIC_COMMENTED",
  COMMENT_LIKED = "COMMENT_LIKED",
  PRODUCT_ORDERED = "PRODUCT_ORDERED",
  PRODUCT_COMMENTED = "PRODUCT_COMMENTED",
}
